/**
 * Демо-справочник сотрудников (единый источник для раздела «Сотрудники»).
 */
export const EMPLOYEES = [
  {
    id: 1,
    name: 'Мирзо Бедил',
    dept: 'ИТ',
    subdept: 'Разработка программного обеспечения',
    position: 'Ведущий специалист',
    email: 'm.bedil@company.local',
    status: 'active',
    hireDate: '01.09.2022',
    birthDate: '15.03.1995',
    gender: 'Мужской',
    mobile: '+998 90 123 45 67',
    telegram: '@mirzo_bedil',
    contractType: 'Полный рабочий день',
    manager: 'Руслан Камолов',
    vacationBalance: { total: 28, used: 9 },
  },
  {
    id: 2,
    name: 'Сардор Тошматов',
    dept: 'ИТ',
    subdept: 'Разработка программного обеспечения',
    position: 'Главный специалист',
    email: 's.toshmatov@company.local',
    status: 'active',
    hireDate: '12.03.2023',
    birthDate: '04.07.1993',
    gender: 'Мужской',
    mobile: '+998 91 234 56 78',
    telegram: '@sardor_t',
    contractType: 'Полный рабочий день',
    manager: 'Руслан Камолов',
    vacationBalance: { total: 28, used: 5 },
  },
  {
    id: 3,
    name: 'Нилуфар Юсупова',
    dept: 'HR',
    subdept: 'Подбор и адаптация персонала',
    position: 'Ведущий специалист',
    email: 'n.yusupova@company.local',
    status: 'active',
    hireDate: '20.06.2021',
    birthDate: '11.02.1991',
    gender: 'Женский',
    mobile: '+998 93 345 67 89',
    telegram: '@nilufar_hr',
    contractType: 'Полный рабочий день',
    manager: 'Зарина Хасанова',
    vacationBalance: { total: 28, used: 3 },
  },
  {
    id: 4,
    name: 'Жасур Мирзаев',
    dept: 'HR',
    subdept: 'Кадровый учёт и кадровое делопроизводство',
    position: 'Специалист',
    email: 'j.mirzaev@company.local',
    status: 'active',
    hireDate: '15.01.2024',
    birthDate: '28.09.1996',
    gender: 'Мужской',
    mobile: '+998 94 456 78 90',
    telegram: '—',
    contractType: 'Полный рабочий день',
    manager: 'Зарина Хасанова',
    vacationBalance: { total: 28, used: 6 },
  },
  {
    id: 5,
    name: 'Малика Рахимова',
    dept: 'ИТ',
    subdept: 'Обеспечение качества и тестирование',
    position: 'Эксперт',
    email: 'm.rakhimova@company.local',
    status: 'active',
    hireDate: '08.04.2023',
    birthDate: '19.12.1994',
    gender: 'Женский',
    mobile: '+998 95 567 89 01',
    telegram: '@malika_qa',
    contractType: 'Полный рабочий день',
    manager: 'Руслан Камолов',
    vacationBalance: { total: 28, used: 2 },
  },
  {
    id: 6,
    name: 'Бобур Хасанов',
    dept: 'Финансы',
    subdept: 'Бухгалтерский учёт и отчётность',
    position: 'Главный специалист',
    email: 'b.khasanov@company.local',
    status: 'active',
    hireDate: '01.02.2020',
    birthDate: '05.05.1988',
    gender: 'Мужской',
    mobile: '+998 90 678 90 12',
    telegram: '—',
    contractType: 'Полный рабочий день',
    manager: 'Дилноза Атаева',
    vacationBalance: { total: 28, used: 7 },
  },
  {
    id: 7,
    name: 'Руслан Камолов',
    dept: 'ИТ',
    subdept: 'Разработка программного обеспечения',
    position: 'Руководитель направления',
    email: 'r.kamolov@company.local',
    status: 'active',
    hireDate: '10.02.2019',
    birthDate: '08.11.1985',
    gender: 'Мужской',
    mobile: '+998 90 200 00 01',
    telegram: '—',
    contractType: 'Полный рабочий день',
    manager: 'Дилноза Атаева',
    vacationBalance: { total: 28, used: 4 },
  },
  {
    id: 8,
    name: 'Зарина Хасанова',
    dept: 'HR',
    subdept: 'Обучение и корпоративная политика',
    position: 'Ведущий специалист',
    email: 'z.khasanova@company.local',
    status: 'active',
    hireDate: '15.05.2021',
    birthDate: '22.06.1990',
    gender: 'Женский',
    mobile: '+998 90 300 55 55',
    telegram: '@zarina_hr',
    contractType: 'Полный рабочий день',
    manager: 'Нилуфар Юсупова',
    vacationBalance: { total: 28, used: 8 },
  },
  {
    id: 9,
    name: 'Дилноза Атаева',
    dept: 'ИТ',
    subdept: 'Информационная безопасность',
    position: 'Главный специалист',
    email: 'd.ataeva@company.local',
    status: 'active',
    hireDate: '03.01.2020',
    birthDate: '12.04.1988',
    gender: 'Женский',
    mobile: '+998 90 400 10 00',
    telegram: '—',
    contractType: 'Полный рабочий день',
    manager: 'Бобур Хасанов',
    vacationBalance: { total: 28, used: 5 },
  },
]

export const EMPLOYEE_STATUS_LABELS = {
  active: 'Работает',
  vacation: 'В отпуске',
  remote: 'Удалённо',
}
