/**
 * Расширенный профиль для страницы «Мой профиль» (демо по sessionUser.name).
 */
import { EMPLOYEES } from '@/constants/employees'

const BASE = {
  branch: 'Головной офис',
  directorate: '—',
  contractType: 'Полный рабочий день',
  statusLabel: 'Работает',
  status: 'active',
  middleName: '—',
  workplace: 'Головной офис',
  points: 1689,
}

/** Полные карточки для пользователей демо-сессии */
export const PROFILE_PRESETS = {
  'Мирзо Бедил': {
    ...BASE,
    tabNumber: '1001',
    position: 'Ведущий специалист',
    dept: 'ИТ',
    subdept: 'Разработка программного обеспечения',
    directorate: 'ИТ · разработка программного обеспечения',
    hireDate: '01.09.2022',
    timeInCompany: '3 года 7 месяцев',
    internalPhone: '1001',
    lastName: 'Бедил',
    firstName: 'Мирзо',
    gender: 'Мужской',
    birthDate: '15.03.1995',
    age: '31 год',
    idNumber: '4022********9012',
    workPhone: '1001',
    mobile: '+998 90 123 45 67',
    email: 'm.bedil@company.local',
    personalEmail: 'mirzo.bedil@gmail.com',
    telegram: '@mirzo_bedil',
    workplace: 'Блок ИТ, 3-й этаж',
    manager: { name: 'Руслан Камолов', role: 'Руководитель направления · разработка ПО' },
    managers: [
      { name: 'Руслан Камолов', role: 'Непосредственный руководитель · разработка ПО' },
      { name: 'Зарина Хасанова', role: 'HR BP · кадровое сопровождение' },
    ],
    kudos: [
      { title: 'Отличная работа над релизом!', time: '2 дня назад', from: 'Р. Камолов' },
      { title: 'Помощь коллегам', time: 'неделю назад', from: 'Команда ИТ' },
    ],
  },
  'Руслан Камолов': {
    ...BASE,
    tabNumber: '2048',
    position: 'Руководитель направления',
    dept: 'ИТ',
    subdept: 'Разработка программного обеспечения',
    directorate: 'ИТ',
    hireDate: '10.02.2019',
    timeInCompany: '7 лет 2 месяца',
    internalPhone: '2048',
    lastName: 'Камолов',
    firstName: 'Руслан',
    gender: 'Мужской',
    birthDate: '08.11.1985',
    age: '40 лет',
    idNumber: '4011********3456',
    workPhone: '2048',
    mobile: '+998 90 200 00 01',
    email: 'r.kamolov@company.local',
    personalEmail: '—',
    telegram: '—',
    workplace: 'Блок ИТ, 3-й этаж',
    manager: { name: 'Дилноза Атаева', role: 'Финансовый директор · курирование' },
    managers: [
      { name: 'Дилноза Атаева', role: 'Функциональный руководитель' },
      { name: 'Зарина Хасанова', role: 'HR BP' },
    ],
    points: 2100,
    kudos: [{ title: 'Лидер команды', time: '5 дней назад', from: 'HR' }],
  },
  'Зарина Хасанова': {
    ...BASE,
    tabNumber: '3055',
    position: 'HR-менеджер',
    dept: 'HR',
    subdept: 'Кадры',
    directorate: 'HR',
    hireDate: '15.05.2021',
    timeInCompany: '4 года 11 месяцев',
    internalPhone: '3055',
    lastName: 'Хасанова',
    firstName: 'Зарина',
    gender: 'Женский',
    birthDate: '22.06.1990',
    age: '36 лет',
    idNumber: '4033********7890',
    workPhone: '3055',
    mobile: '+998 90 300 55 55',
    email: 'z.khasanova@company.local',
    personalEmail: 'z.khasanova@mail.ru',
    telegram: '@zarina_hr',
    workplace: 'HR, 2-й этаж',
    manager: { name: 'Нилуфар Юсупова', role: 'Руководитель HR-направления' },
    managers: [
      { name: 'Нилуфар Юсупова', role: 'Непосредственный руководитель' },
    ],
    points: 980,
    kudos: [{ title: 'Забота о сотрудниках', time: 'вчера', from: 'Команда' }],
  },
  'Дилноза Атаева': {
    ...BASE,
    tabNumber: '4100',
    position: 'Финансовый аналитик',
    dept: 'Финансы',
    subdept: 'Анализ',
    directorate: 'Финансы',
    hireDate: '03.01.2020',
    timeInCompany: '6 лет 3 месяца',
    internalPhone: '4100',
    lastName: 'Атаева',
    firstName: 'Дилноза',
    gender: 'Женский',
    birthDate: '12.04.1988',
    age: '38 лет',
    idNumber: '4044********1122',
    workPhone: '4100',
    mobile: '+998 90 400 10 00',
    email: 'd.ataeva@company.local',
    personalEmail: 'd.ataeva@inbox.ru',
    telegram: '—',
    workplace: 'Финансы, 4-й этаж',
    manager: { name: 'Бобур Хасанов', role: 'Главный бухгалтер' },
    managers: [
      { name: 'Бобур Хасанов', role: 'Непосредственный руководитель' },
      { name: 'Руслан Камолов', role: 'Согласование проектов' },
    ],
    points: 1540,
    kudos: [{ title: 'Точная отчётность', time: '3 дня назад', from: 'Руководство' }],
  },
}

/**
 * Собирает объект профиля для отображения: пресет или данные из справочника + заглушки.
 */
export function getProfileForUser(session) {
  const name = session?.name || ''
  const preset = PROFILE_PRESETS[name]
  const fromEmp = EMPLOYEES.find(e => e.name === name)

  if (preset) {
    return {
      ...preset,
      fullName: name,
      initials: session?.initials || '??',
      email: preset.email || fromEmp?.email || '—',
    }
  }

  if (fromEmp) {
    return {
      fullName: fromEmp.name,
      initials: session?.initials || '??',
      tabNumber: String(1000 + fromEmp.id),
      position: fromEmp.position,
      dept: fromEmp.dept,
      subdept: fromEmp.subdept,
      directorate: `${fromEmp.dept} · ${fromEmp.subdept}`,
      email: fromEmp.email,
      statusLabel: 'Работает',
      status: 'active',
      branch: BASE.branch,
      contractType: BASE.contractType,
      hireDate: '—',
      timeInCompany: '—',
      internalPhone: '—',
      lastName: fromEmp.name.split(/\s+/).slice(-1)[0] || '—',
      firstName: fromEmp.name.split(/\s+/)[0] || '—',
      middleName: '—',
      gender: '—',
      birthDate: '—',
      age: '—',
      idNumber: '—',
      workPhone: '—',
      mobile: '—',
      personalEmail: '—',
      telegram: '—',
      workplace: BASE.workplace,
      manager: { name: '—', role: '—' },
      managers: [],
      points: 100,
      kudos: [],
    }
  }

  return {
    fullName: name || 'Сотрудник',
    initials: session?.initials || '?',
    tabNumber: '—',
    position: '—',
    statusLabel: 'Работает',
    status: 'active',
    branch: BASE.branch,
    email: '—',
    manager: { name: '—', role: '—' },
    managers: [],
    dept: '—',
    subdept: '—',
    directorate: '—',
    contractType: BASE.contractType,
    hireDate: '—',
    timeInCompany: '—',
    internalPhone: '—',
    lastName: '—',
    firstName: '—',
    middleName: '—',
    gender: '—',
    birthDate: '—',
    age: '—',
    idNumber: '—',
    workPhone: '—',
    mobile: '—',
    personalEmail: '—',
    telegram: '—',
    workplace: '—',
    points: 0,
    kudos: [],
  }
}
